name: Compile GTK+ Application
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: actions/setup-linux-gcc@v3
        with:
          version: 12.x
      - name: Install GTK+ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev build-essential
      - name: Build for Linux
        run: |
          mkdir -p build/linux
          gcc -o build/linux/my-gtk-app main.c $(pkg-config --cflags --libs gtk+-3.0)
  
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msys2Arch: 'msys'
          msys2Path: true
          # 选择需要的组件，这里选择了 MinGW 64位 GCC 和 GTK3
          msys2Mirrors: 'https://mirrors.ustc.edu.cn/msys2/'
          # 安装必要的开发工具和依赖
          install:
            - base-devel
            - mingw-w64-x86_64-gcc
            - mingw-w64-x86_64-gtk3
      - name: Install GTK+ dependencies
        run: |
          pacman -S --needed base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-gtk3
      - name: Build for Windows
        run: |
          mkdir -p build/windows
          x86_64-w64-mingw32-gcc -o build/windows/my-gtk-app.exe main.c ^
               $(pkg-config --cflags --libs gtk+-3.0)
