name: Build and Test

on:
  push:
    branches: ["*"]

env:
  MSYS_MIRROR: https://mirrors.ustc.edu.cn/msys2/
  MSYS pacman pacman_options: --noconfirm

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msys2Arch: 'mingw64'
          msys2Path: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-gdk-pixbuf2
            pkg-config
      
      - name: Install additional dependencies
        shell: msys2 {0}
        run: |
          pacman -S --needed --noconfirm mingw-w64-x86_64-gdk-pixbuf2 mingw-w64-x86_64-pango mingw-w64-x86_64-gtk4 mingw-w64-x86_64-gtk4-devel mingw-w64-x86_64-toolkit
      - name: Build GTK+ application
        shell: msys2 {0}
        run: |
          echo "Building GTK+ application..."
          mkdir build
          mkdir dist
          cd build
          x86_64-w64-mingw32-gcc -o ../dist/main.exe ../main.cpp $(pkg-config --cflags --libs gtk4)
          LIBS=$(pkg-config --libs gtk4)
          pkg-config --cflags --libs gtk4
          ls /mingw64/lib
          ls /mingw64/lib/glib-2.0
          MINGW_BIN_DIR="/c/msys64/mingw64/bin"
          for lib in $LIBS; do
              echo $lib
              if [[ $lib == "-l"* ]]; then
                  dll_name=$(echo $lib | cut -c3-).dll
                  dll_path=$MINGW_BIN_DIR/$dll_name
                  if [ -f "$dll_path" ]; then
                      cp "$dll_path" ../dist/
                      if [ $? -ne 0 ]; then
                          echo "Error: Failed to copy $dll_path"
                          exit 1
                      fi
                  else
                      echo "Warning: $dll_path not found."
                  fi
              fi
          done
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ${{ github.workspace }}/dist/*