name: Build and Test

on:
  push:
    branches: ["*"]

env:
  MSYS_MIRROR: https://mirrors.ustc.edu.cn/msys2/
  MSYS pacman pacman_options: --noconfirm

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msys2Arch: 'mingw64'
          msys2Path: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-pango
            mingw-w64-x86_64-gdk-pixbuf2
      
      - name: Install additional dependencies
        shell: cmd
        run: |
          pacman -S --needed --noconfirm ^
                 mingw-w64-x86_64-gdk-pixbuf2 ^
                 mingw-w64-x86_64-pango ^
                 mingw-w64-x86_64-gtk3
          ^
      - name: Build GTK+ application
        shell: cmd
        run: |
          echo "Building GTK+ application..."
          mkdir build
          cd build
          x86_64-w64-mingw32-gcc -o ../dist/main.exe ^
                 ..\main.c ^
                 $(pkg-config --cflags --libs gtk+-3.0)